name: montirku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  image_picker: ^0.8.7+4
  firebase_core: ^2.24.2
  firebase_database: ^10.3.4
  cloud_firestore: ^4.15.0
  crypto: ^3.0.3
  shared_preferences: ^2.0.18
  flutter_map: ^7.0.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bengkel/
    - assets/images/pelanggan/
    - assets/images/montir/
